name: Repo sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: sync with external repo
        run: |
          #https://medium.com/@_oleksii_/how-to-synchronize-two-remote-git-repositories-e63b78892901
          git remote -v
          git remote add upstream https://samsmithnz@dev.azure.com/samsmithnz/AzureDevOpsSyncSource/_git/AzureDevOpsSyncSource
          git remote -v
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push


