name: Repo sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: sync with external repo
        run: |
          #git clone https://samsmithnz@dev.azure.com/samsmithnz/AzureDevOpsSyncSource/_git/AzureDevOpsSyncSource
          git remote -v
          git remote add upstream https://samsmithnz@dev.azure.com/samsmithnz/AzureDevOpsSyncSource/_git/AzureDevOpsSyncSource
          #git remote add newRepo https://github.com/samsmithnz/AzureDevOpsSyncToGitHub
          #git remote -v


